# Site configuration
title: Jack's Dev Blog
email: digitalbricklayer@gmail.com
description: >
  This site is the digital home of Jack Hughes a journeyman programmer from Leeds, UK. He is a professional software developer specialising in the .NET stack. He currently works for OPENXTRA Ltd..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://digitalbricklayer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mrjackhughes
github_username:  digitalbricklayer
copyright_notice: "Copyright &copy; 2015-2017 Jack Hughes. All rights reserved."
permalink: /:slug/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run-dev-server.sh

google_analytics: UA-71383-42
