# Site configuration
title: Jack's Dev Blog
email: your-email@domain.com
description: >
  The digital home of Jack Hughes a journeyman programmer from Leeds, UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mrjackhughes
github_username:  digitalbricklayer

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

