# Site configuration
title: Jack's Dev Blog
email: your-email@domain.com
description: >
  This site is the digital home of Jack Hughes a journeyman programmer from Leeds, UK. He is a professional software developer specialising in the .NET stack. He currently works for OPENXTRA Ltd..
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mrjackhughes
github_username:  digitalbricklayer
copyright_notice: "Copyright &copy; 2015-2017 Jack Hughes. All rights reserved."

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
